let width = 400;
let height = 400;

let furnitureTypes = [
  "Bathroom Cabinet Drawer",
  "Bathroom Cabinet",
  "Bathroom Mirror",
  "Bathroom Sink Square",
  "Bathroom Sink",
  "Bathtub",
  "Bear",
  "Bed Bunk",
  "Bed Double",
  "Bed Single",
  "Bench Cushion Low",
  "Bench Cushion",
  "Bench",
  "Bookcase Closed Doors",
  "Bookcase Closed Wide",
  "Bookcase Closed",
  "Bookcase Open Low",
  "Bookcase Open",
  "Books",
  "Cabinet Bed Drawer Table",
  "Cabinet Bed Drawer",
  "Cabinet Bed",
  "Cabinet Television Doors",
  "Cabinet Television",
  "Cardboard Box Closed",
  "Cardboard Box Open",
  "Ceiling Fan",
  "Chair Cushion",
  "Chair Desk",
  "Chair Modern Cushion",
  "Chair Modern Frame Cushion",
  "Chair Rounded",
  "Chair",
  "Coat Rack Standing",
  "Coat Rack",
  "Computer Keyboard",
  "Computer Mouse",
  "Computer Screen",
  "Desk Corner",
  "Desk",
  "Doorway Front",
  "Doorway Open",
  "Doorway",
  "Dryer",
  "Floor Corner Round",
  "Floor Corner",
  "Floor Full",
  "Floor Half",
  "Hood Large",
  "Hood Modern",
  "Kitchen Bar End",
  "Kitchen Bar",
  "Kitchen Blender",
  "Kitchen Cabinet Corner Inner",
  "Kitchen Cabinet Corner Round",
  "Kitchen Cabinet Drawer",
  "Kitchen Cabinet Upper Corner",
  "Kitchen Cabinet Upper Double",
  "Kitchen Cabinet Upper Low",
  "Kitchen Cabinet Upper",
  "Kitchen Cabinet",
  "Kitchen Coffee Machine",
  "Kitchen Fridge Built In",
  "Kitchen Fridge Large",
  "Kitchen Fridge Small",
  "Kitchen Fridge",
  "Kitchen Microwave",
  "Kitchen Sink",
  "Kitchen Stove Electric",
  "Kitchen Stove",
  "Lamp Round Floor",
  "Lamp Round Table",
  "Lamp Square Ceiling",
  "Lamp Square Floor",
  "Lamp Square Table",
  "Lamp Wall",
  "Laptop",
  "Lounge Chair Relax",
  "Lounge Chair",
  "Lounge Design Chair",
  "Lounge Design Sofa Corner",
  "Lounge Design Sofa",
  "Lounge Sofa Corner",
  "Lounge Sofa Long",
  "Lounge Sofa Ottoman",
  "Lounge Sofa",
  "Paneling",
  "Pillow Blue Long",
  "Pillow Blue",
  "Pillow Long",
  "Pillow",
  "Plant Small 1",
  "Plant Small 2",
  "Plant Small 3",
  "Potted Plant",
  "Radio",
  "Rug Doormat",
  "Rug Rectangle",
  "Rug Round",
  "Rug Rounded",
  "Rug Square",
  "Shower Round",
  "Shower",
  "Side Table Drawers",
  "Side Table",
  "Speaker Small",
  "Speaker",
  "Stairs Corner",
  "Stairs Open Single",
  "Stairs Open",
  "Stairs",
  "Stool Bar Square",
  "Stool Bar",
  "Table Cloth",
  "Table Coffee Glass Square",
  "Table Coffee Glass",
  "Table Coffee Square",
  "Table Coffee",
  "Table Cross Cloth",
  "Table Cross",
  "Table Glass",
  "Table Round",
  "Table",
  "Television Antenna",
  "Television Modern",
  "Television Vintage",
  "Toaster",
  "Toilet Square",
  "Toilet",
  "Trashcan",
  "Wall Corner Rond",
  "Wall Corner",
  "Wall Doorway Wide",
  "Wall Doorway",
  "Wall Half",
  "Wall Window Slide",
  "Wall Window",
  "Wall",
  "Washer Dryer Stacked",
  "Washer"
];

let directions = [
  "NE",
  "NW",
  "SE",
  "SW"
];

let images = [];
let imageScale = 0.5;

let lastTurn = 0;

let turnDelay = 100;
let placePrecision = 0.1;

let selected = 0;
let placed = [];
for (let i = 0; i < width * placePrecision; i++) {
  placed.push([]);
  for (let j = 0; j < height * placePrecision; j++)
    placed[i].push(0);
}